[database]
url = "postgres://postgres:123456@localhost:5432/postgres"
max_connections = 10

[ckb]
url = "https://testnet.ckb.dev/"
network = "ckb_testnet"

[server]
host = "0.0.0.0"
port = 3000

[payment]
platform_address = "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwu8lmjcalepgp5k6d4j0mtxwww68v9m6qz0q8ah"
platform_private_key = "0x88179b7e387921a193f459859d8ff461e973a93a449b4930179928dbc53a04ba"
# Minimum withdrawal amount (CKB)
min_withdrawal_amount = 65
